---
title: "Novum R-ganum"
output: 
  html_document: 
    theme: readable
---

## About [[**.html**](blog_entries/2018/nrg00/nrg00.html)]
> 1. R tutorials made with psychologists in mind
> 2. Statistics & Methods

## 2018
> * Testing Indirect Effects/Mediation in R [[**.html**](blog_entries/2018/nrg01/nrg01.html)]
> * Testing Conditional Indirect Effects in R [[**.html**](blog_entries/2018/nrg02/nrg02.html)]
> * R for Psychology Research: A Crash Course [[**.html**](blog_entries/2018/nrg03/nrg03.html)]
> * Testing Within-Subjects Contrasts (Repeated Measures) in R [[**.html**](blog_entries/2018/nrg07/nrg07.html)]
> * Testing Between-Subjects Contrasts in R [[**.html**](blog_entries/2018/nrg06/nrg06.html)]
> * The Covariance Structures in Mixed Effects/Multilevel Models in R
> * Using Principal Components or Factor Analysis in Social Psychology
> * Probing and Plotting Interactions in R [[**.html**](blog_entries/2018/nrg04/nrg04.html)]
> * Plotting Adjusted Associations in R[[**.html**](blog_entries/2018/nrg08/nrg08.html)]