---
title: "Presentations"
output: 
  html_document: 
    theme: readable
---

## 2018
> * **Michalak, N.M.**, & Ackerman, J.M. (2018). Infectious disease has many faces: Are they all the same? (new data presented) Presentation given at the Human Behavior and Evolution Society Conference, Amsterdam.
> * **Michalak, N.M.**, & Ackerman, J.M. (2018). Infectious disease has many faces: Are they all the same? Poster presented at the Nonverbal Preconference at the Society for Personality and Social Psychology Convention, Atlanta, GA. [[**Poster**](https://github.com/nmmichalak/nicholas_michalak/raw/master/presentations/2018/2018SPSP_michalak_nonvernal_preconference.pptx)]
> * **Michalak, N.M.**. Disease cues in the face. Presentation given at the Social Psychology Area Recruitment Weekend Data Blitz at the University of Michigan, Ann Arbor, MI. [[**Slides**](https://github.com/nmmichalak/nicholas_michalak/raw/master/presentations/2018/2018W_psychology_recruitment_social_area_datablitz.pptx)]

## 2017
> * **Michalak, N.M.**, Takahashi, K.J. (2017). Methods Reform: Motivations, challenges, and best practices. Presentation given at Dal Cin Lab Meeting at the University of Michigan, Ann Arbor, MI.
> * **Michalak, N.M.**, Takahashi, K.J., & Lee, J.Y. (2017). Preregistration. Presentation given at Psychology Methods Hour at the University of Michigan, Ann Arbor, MI. [[**Slides**](http://sites.lsa.umich.edu/methods-hour/wp-content/uploads/sites/453/2017/11/2017F_methods_hour_preregistration.pptx)]
> * **Michalak, N.M.**, & Ackerman, J.M. (2017). Infectious disease has many faces: Are they all the same? Presentation given at Social Area Brown Bag at the University of Michigan, Ann Arbor, MI. [[**Slides**](https://github.com/nmmichalak/nicholas_michalak/raw/master/presentations/2017/2017F_umich_social_brownbag_michalak.pptx)]
> * **Michalak, N.M.** (2017). What's MTurk? Presentation given at the Michigan Psychology Department Orientation, Ann Arbor, MI.
> * **Michalak, N.M.**, & Ackerman, J.M. (2017). What does infectious disease look like in the mind? A Reverse Correlation Approach. Presentation given at the at the Human Behavior and Evolution Society Conference, Boise, ID. [[**Slides**](https://github.com/nmmichalak/nicholas_michalak/raw/master/presentations/2017/2017HBES_michalak_ackerman.pptx)]
> * **Michalak, N.M.** (2017). What makes a good test? Presentation given at Psychology Methods Hour, The University of Michigan, Ann Arbor, MI. [[**Slides & R code**](https://sites.lsa.umich.edu/methods-hour/winter-2017/)]
> * **Michalak, N.M.**, & Ackerman, J.M. (2017). What does infectious disease look like in the mind? A Reverse Correlation Approach. Presentation given at the Evolutionary Psychology Preconference at the Society for Personality and Social Psychology Convention, San Antonio, TX. [[**Slides**](https://github.com/nmmichalak/nicholas_michalak/raw/master/presentations/2017/2017SPSP_evolutionary_psychology_preconference_michalak_ackerman.pptx)]
> * **Michalak, N.M.**, & Edelstein, R.S. (2017). Power play: Status-sensitive men may strategically modulate their desire for intergroup dominance (new data presented). Poster presented at the Society for Personality and Social Psychology Convention, San Antonio, TX. [[**Poster**](https://github.com/nmmichalak/nicholas_michalak/raw/master/presentations/2017/2017SPSP_intergroup_processes_poster_michalak_edelstein.pptx)]

## 2016
> * **Michalak, N.M.** (2016). What's MTurk? Presentation given at the Michigan Psychology Department Orientation, Ann Arbor, MI. [[**Slides**](https://github.com/nmmichalak/nicholas_michalak/raw/master/presentations/2016/2016W_michigan_psychology_orientation_michalak.pptx)]
> * **Michalak, N.M.**, & Edelstein, R.S. (2016) Power play: Status-sensitive men (indexed by their change in testosterone) may strategically modulate their desire for intergroup dominance. Presentation given at the Connecting Minds in Social Neuroendocrinology and Evolution Preconference at the Human Behavior and Evolution Society Conference, Vancouver, Canada. [[**Slides**](https://github.com/nmmichalak/nicholas_michalak/raw/master/presentations/2016/2016HBES_social_neuroendocrinology_preconference_michalak_edelstein.pptx)]
